# -*- coding: utf-8 -*-
# Multi-day routes. Every id is validated against the built dataset; unknown ids are dropped
# with a warning at build time, and any route left with fewer than three stops is discarded.

TRIPS = [
{"id":"r-istanbul-essential","title":"Istanbul: The Essential Five Days","region":"Marmara","days":"5 days","mode":"walk","ap":"IST","hub":"Sultanahmet, Istanbul","season":"Apr–Jun, Sep–Nov","stay":["Istanbul","Sultanahmet for the monuments, Karaköy or Cihangir for everything else"],
 "d1":[["hagia-sophia","Start here, first thing, before the queue forms"],["blue-mosque-sultanahmet","Across the square — check prayer times"],["hippodrome-constantinople","The obelisks between the two, five minutes"],["basilica-cistern","Cool, dark and a good midday move"]],
 "d2":[["topkapi-palace","Give it three hours; the Harem is a separate ticket and worth it"],["grand-bazaar-istanbul","Enter from Nuruosmaniye for the handsome gate"],["spice-bazaar-eminonu","Then down to the water through the han district"],["suleymaniye-mosque","End on the terrace at sunset with the Golden Horn below"]],
 "d3":[["chora-kariye","Taxi out early for the mosaics"],["walls-of-constantinople","Walk a stretch of the land walls from Edirnekapı"],["balat","Coloured houses and coffee, downhill from the walls"],["fener","The Greek college and the Patriarchate next door"]],
 "d4":[["bosphorus-ferry","Take the long ferry up the European shore"],["anadolu-kavagi","Get off at the top for fish and the Yoros castle climb"],["rumelihisari","On the way back, the fortress at the narrows"],["arnavutkoy-bosphorus","Dinner among the wooden yalıs"]],
 "d5":[["kadikoy","Cross to the Asian side for the market and the fish"],["camlica-hill","Up the hill for the whole city at once"],["kuzguncuk","The prettiest street in Istanbul, and the least visited"],["karakoy","Finish with meyhane tables under Galata"]],
 "note":"Buy an İstanbulkart at the airport and load it heavily — it works on ferries, trams, metro and the funiculars, and the ferries are the best value transport in Europe."},

{"id":"r-istanbul-other","title":"The Other Istanbul: Islands, Forest and Black Sea","region":"Marmara","days":"3 days","mode":"boat","ap":"IST","hub":"Kabataş, Istanbul","season":"May–Jun, Sep–Oct","stay":["Büyükada","Wooden mansion hotels; book ahead, the island fills at weekends"],
 "d1":[["buyukada","Ferry from Kabataş; no cars, hire a bicycle"],["heybeliada","Hop one island back for the naval school pines"],["burgazada","Quieter still, and the best swimming platform"]],
 "d2":[["belgrad-forest","Out to the forest early, walk the reservoir loop"],["maglova-aqueduct","Sinan's aqueduct in the woods, almost nobody there"],["polonezkoy","Lunch in the Polish village, then back"]],
 "d3":[["sile","Up to the Black Sea coast and the white lighthouse"],["agva","Between two rivers, kayak or just eat"],["riva","Castle ruin and a wide empty beach on the way back"]],
 "note":"All three days are doable without a car, but the Şile–Ağva day is far easier with one. The islands are miserable on summer weekends and lovely on a Tuesday in May."},

{"id":"r-canakkale","title":"Troy, Gallipoli and the Two Islands","region":"Marmara","days":"4 days","mode":"car","ap":"CKZ","hub":"Çanakkale","season":"May–Jun, Sep–Oct","stay":["Çanakkale","Waterfront hotels; Bozcaada for the last two nights if you can"],
 "d1":[["troy","The layers take a guide or a good audio guide to make sense"],["canakkale-1915-bridge","The longest suspension span in the world, on the way north"],["kilitbahir-castle","Heart-shaped Ottoman fortress across the strait"]],
 "d2":[["gallipoli-battlefields","A full day; the cemeteries are spread over 30 km"],["anzac-cove","The landing beach and the Lone Pine memorial above"]],
 "d3":[["bozcaada","Ferry from Geyikli — vineyards, a castle and empty beaches"]],
 "d4":[["assos-behramkale","The Athena temple above the Aegean, best at sunset"],["adatepe-yesilyurt","Stone villages on the skirts of Mount Ida"],["kaz-daglari-mount-ida","Walk into the national park for the waterfalls"]],
 "note":"Gökçeada is the bigger, wilder island and needs its own two days — swap it for Bozcaada if you want walking and Greek villages rather than wine."},

{"id":"r-bursa-iznik","title":"Bursa, İznik and the Ottoman Cradle","region":"Marmara","days":"3 days","mode":"car","ap":"YEI","hub":"Bursa","season":"Apr–Jun, Sep–Oct","stay":["Bursa","Old-town hotels near the Hanlar district"],
 "d1":[["bursa-grand-mosque","The twenty domes and the calligraphy inside"],["bursa-hanlar-district","Koza Han for silk and tea in the courtyard"],["yesil-complex-bursa","The green tiles that named the district"],["muradiye-complex-bursa","Ten royal tombs in a walled garden, and hardly anyone in them"]],
 "d2":[["cumalikizik","Ottoman village on the mountain skirt, breakfast with jam"],["uludag","Cable car up for the meadows, or the snow in winter"]],
 "d3":[["iznik","Roman walls, the Hagia Sophia church and the tile workshops"],["golyazi","Lakeside Greek village on a peninsula, almost untouched"],["trilye-zeytinbagi","Olive oil, a Byzantine church and lunch by the Marmara"]],
 "note":"Bursa is close enough to Istanbul that most people day-trip it and see a quarter of what is there. Three days is the right amount."},

{"id":"r-aegean-classics","title":"The Aegean Classics: Ephesus, Pergamon and İzmir","region":"Aegean","days":"5 days","mode":"car","ap":"ADB","hub":"İzmir","season":"Apr–May, Sep–Oct","stay":["Selçuk","Or Şirince up the hill for the village version"],
 "d1":[["kemeralti-izmir","The bazaar first, and a fish lunch off Alsancak"],["agora-of-smyrna","Roman agora in the middle of the city"],["asansor-izmir","The old lift up the cliff, for the sunset view"]],
 "d2":[["ephesus","Go at opening; enter at the upper gate and walk downhill"],["temple-of-artemis-ephesus","One column left of a wonder of the world"],["basilica-of-st-john-selcuk","Above the town, with the best view over the plain"]],
 "d3":[["sirince","Village morning, fruit wine and a slow breakfast"],["camlik-railway-museum","A yard full of retired steam engines, better than it sounds"],["tire","Market town with a Wednesday bazaar worth planning around"]],
 "d4":[["pergamon","Cable car up to the acropolis and the vertiginous theatre"],["asklepion-pergamon","The healing sanctuary below, with its tunnel"],["red-basilica-bergama","The vast brick temple of Serapis in the town"]],
 "d5":[["birgi","Timber-and-plaster Ottoman houses, a UNESCO town almost nobody visits"],["odemis","Market and museum on the way back"],["bozdag-odemis","Up into the pines to Gölcük lake for the air"]],
 "note":"Ephesus and Pergamon both bake by eleven. Both are two-hour sites done well and eight-hour sites done badly — start at opening and take the afternoon off."},

{"id":"r-cesme-peninsula","title":"Çeşme, Karaburun and the Urla Vineyards","region":"Aegean","days":"4 days","mode":"car","ap":"ADB","hub":"Çeşme","season":"May–Jun, Sep–Oct","stay":["Alaçatı","Stone-house boutique hotels; expensive in August, reasonable in May"],
 "d1":[["urla","Vineyards and a very good food scene 40 min from the airport"],["sigacik","Walled Seljuk village with a Sunday market"],["teos","The Dionysus temple in the olive groves next door"]],
 "d2":[["alacati","Stone streets, then the windsurf bay in the afternoon"],["cesme-castle","Genoese walls over the harbour"],["ilica-cesme","Thermal water rising into the shallows of the bay"]],
 "d3":[["erythrae-ildir","Ruins scattered through a fishing village"],["karaburun","The long empty road up the peninsula"],["mordogan","Swim, eat, drive back at sunset"]],
 "d4":[["foca","Monk-seal coast, the old harbour and grilled fish"],["yenifoca","Quieter twin up the coast"],["gediz-delta","Flamingos on the way back to the airport"]],
 "note":"The meltemi blows hard here in July and August — perfect for windsurfing at Alaçatı, less perfect for lying on a beach."},

{"id":"r-caria-menderes","title":"Caria and the Maeander: Aphrodisias to Lake Bafa","region":"Aegean","days":"5 days","mode":"car","ap":"ADB","hub":"Aydın","season":"Apr–May, Oct","stay":["Lake Bafa","Herakleia guesthouses on the lake shore — the best base in the region"],
 "d1":[["aphrodisias","The most complete ancient city in Türkiye, and the stadium is the reason"],["karacasu","Lunch in the potters' town below"],["nysa-on-the-maeander","Theatre and tunnel above the valley"]],
 "d2":[["priene","Hillside grid city with the Athena temple columns"],["miletus","The vast theatre on the silted-up harbour"],["didyma","The oracle temple, with columns you stand under"]],
 "d3":[["lake-bafa","Boat to the islands and the Byzantine monasteries"],["herakleia-under-latmos","Ruins woven through a living village under Latmos"],["latmos-rock-paintings","Prehistoric figures on the rock, with a guide"]],
 "d4":[["labraunda","Terraced Zeus sanctuary high in the pines above Milas"],["euromos","Sixteen standing columns right beside the road"],["milas","Beçin castle and the Wednesday market"]],
 "d5":[["dilek-peninsula-national-park","Beaches under wooded cliffs"],["cave-of-zeus-guzelcamli","Cold green swimming hole by the entrance"],["kusadasi","Or skip it and go straight back to the airport"]],
 "note":"Aphrodisias sits at 600 m and stays bearable when the coast does not. Lake Bafa in the evening, with the light going pink on Latmos, is the memory people keep."},

{"id":"r-bodrum","title":"The Bodrum Peninsula, Slowly","region":"Aegean","days":"4 days","mode":"car","ap":"BJV","hub":"Bodrum","season":"May–Jun, Sep–Oct","stay":["Gümüşlük","Sea-level fish restaurants and no nightclubs"],
 "d1":[["bodrum-castle","The castle and its underwater archaeology museum"],["mausoleum-halicarnassus","What is left of a wonder, in the middle of town"],["theatre-of-halicarnassus","Above the road, free, and best at sunset"]],
 "d2":[["gumusluk-myndos","Wade the causeway to Rabbit Island at dusk"],["yalikavak","Marina glamour if you want it"],["gundogan-bodrum","Quiet bay with a Byzantine chapel in the hills"]],
 "d3":[["akyarlar","Southern beaches and the Aspat cone above"],["karaincir","Shallow, sandy and good for a long lazy day"],["bitez","Tangerine groves behind the beach"]],
 "d4":[["pedasa","Lelegian ruins in the hills above Konacık"],["becin-castle","The Menteşe capital on its bluff"],["iasos","Harbour ruins on a peninsula, on the way to Milas"]],
 "note":"August on this peninsula is expensive and gridlocked. The same place in late September has warm water, empty roads and half the prices."},

{"id":"r-datca-hisaronu","title":"Datça, Bozburun and the Sunken Road","region":"Aegean","days":"5 days","mode":"boat","ap":"DLM","hub":"Marmaris","season":"May–Jun, Sep–Oct","stay":["Selimiye","Waterfront pensions on the Bozburun peninsula"],
 "d1":[["marmaris","Arrive, walk the castle and the old quarter"],["marmaris-national-park","Pines down to the water on the coast road"],["turunc","First proper swim, in a bay under the cliffs"]],
 "d2":[["orhaniye-kizkumu","Walk out into the middle of the bay on the sand spit"],["selimiye-marmaris","Fish dinner on the quay"],["bozburun","Gulet yards and the quietest harbour on the coast"]],
 "d3":[["eski-datca","Bougainvillea and stone lanes, then on down the peninsula"],["palamutbuku","Pebble beach with startlingly clear water"],["knidos","Two harbours and the sunset at the peninsula's tip"]],
 "d4":[["sedir-island","Cleopatra's beach — look, do not take the sand"],["akyaka","Kite-surf bay and Gökova river kayaking"],["yuvarlakcay","Plane trees over cold water, trout for lunch"]],
 "d5":[["koycegiz-lake","Boat across the lake to the springs"],["sultaniye-hot-springs","Sulphur mud and 39 °C water on the shore"],["dalyan","Up the reed channels below the rock tombs"],["iztuzu-beach","Turtle beach at the river mouth — closed at night in nesting season"]],
 "note":"The Bozburun and Datça peninsulas are where Turkish sailors go on holiday. Roads are slow and winding; do not plan more than two stops a day."},

{"id":"r-lycia-west","title":"Western Lycia: Fethiye to Patara","region":"Aegean","days":"6 days","mode":"car","ap":"DLM","hub":"Fethiye","season":"Apr–May, Sep–Oct","stay":["Kalkan","Or Faralya on the cliff above Butterfly Valley for the wilder version"],
 "d1":[["fethiye","Harbour town, fish market where they cook what you buy"],["tomb-of-amyntas","Rock-cut temple facade above the town, go at sunset"],["kayakoy","The abandoned Greek town on the hill behind"]],
 "d2":[["oludeniz","The lagoon early, before the paragliders land"],["babadag-fethiye","Cable car up, or jump off it with a pilot"],["butterfly-valley-fethiye","Boat in from Ölüdeniz for the afternoon"]],
 "d3":[["kabak-faralya","Cliff-top village, then the steep path down to Kabak bay"],["lycian-way-western-half","Walk a section — the Faralya–Kabak stretch is the classic"]],
 "d4":[["tlos","Acropolis, rock tombs and a Roman bath with a view"],["saklikent-gorge","Wade the cold water into the canyon"],["pinara","Cliff face of honeycomb tombs, usually deserted"]],
 "d5":[["letoon","Three temples and a flooded nymphaeum with frogs"],["xanthos-ancient-city","The Lycian capital and its pillar tombs"],["kalkan-town","Bougainvillea lanes and dinner on a roof terrace"]],
 "d6":[["patara-ancient-city","The council chamber, the theatre, and 18 km of empty sand"],["kaputas-beach","The famous cove from the road above, then the steps down"]],
 "note":"Patara's beach closes at dusk from May to September for the loggerhead turtles. That is a feature, not a problem — go at eight in the morning instead."},

{"id":"r-lycia-east","title":"Eastern Lycia: Kekova, Olympos and the Flames","region":"Mediterranean","days":"5 days","mode":"car","ap":"AYT","hub":"Antalya","season":"Apr–May, Sep–Oct","stay":["Kaş","Then two nights in Çıralı for the second half"],
 "d1":[["kas-town","Arrive, walk the harbour, the Hellenistic theatre at sunset"],["kas-diving","Or dive — the visibility here is the best in the country"]],
 "d2":[["kekova-sunken-city","Boat over the drowned Lycian streets"],["simena-kalekoy","Climb to the castle among the sarcophagi"],["ucagiz-teimiussa","Tombs standing in the shallows at the village edge"]],
 "d3":[["myra-ancient-city","Cliff tombs above a Roman theatre"],["st-nicholas-church-demre","Where Santa Claus was actually bishop"],["andriake-harbour","Hadrian's granary and the marshland birds"]],
 "d4":[["olympos-ancient-city","Ruins in the undergrowth, ending at the beach"],["yanartas-chimaera","Walk up after dark for the flames coming out of the rock"],["cirali-beach","Pebble beach, turtle nests, no concrete"]],
 "d5":[["phaselis-ancient-city","Three harbours and a swim off the ancient quay"],["tahtali-dagi-cable-car","Cable car to 2,365 m for the whole coast at once"],["antalya-kaleici","Finish in the old town for dinner"]],
 "note":"The Chimaera flames are far better after dark than at dusk, and the path is rough — take a torch, not a phone light."},

{"id":"r-pamphylia","title":"Pamphylia: Four Ruined Cities in Three Days","region":"Mediterranean","days":"3 days","mode":"car","ap":"AYT","hub":"Antalya","season":"Mar–May, Oct–Nov","stay":["Antalya","Kaleiçi for the old-town courtyards"],
 "d1":[["perge-ancient-city","Colonnaded street, stadium and the best-preserved gate"],["aspendos-theatre","The Roman theatre that still works as a theatre"],["sillyon-ancient-city","A flat-topped acropolis nobody visits"]],
 "d2":[["side-ancient-town","Temple of Apollo on the point at sunset"],["manavgat-waterfall","Wide rather than tall, and a good tea stop"],["seleukeia-pamphylia","Ruins in a pine forest above Manavgat"]],
 "d3":[["termessos-ancient-city","The mountain city Alexander declined to besiege — a real climb"],["karain-cave","Palaeolithic layers going back half a million years"],["duden-waterfalls","Upper falls in the afternoon, walk behind the curtain"]],
 "note":"Termessos is a 1,000 m hike in and out with no shade at the top — take twice the water you think you need and go early."},

{"id":"r-taurus-backroads","title":"Taurus Backroads: Canyons, Cedars and Ormana","region":"Mediterranean","days":"3 days","mode":"car","ap":"AYT","hub":"Antalya","season":"May–Jun, Sep–Oct","stay":["Ormana","Restored cumba houses in the village"],
 "d1":[["koprulu-canyon","Raft the Köprüçay, or just walk the Roman bridge"],["selge-ancient-city","Theatre in the rocks above, reached by a mad little road"]],
 "d2":[["ormana-village","Interlocking timber houses, unlike anywhere else in Türkiye"],["altinbesik-cave","Boat into a flooded cave through a rock arch"],["ibradi-town","Ottoman stone houses and lunch"]],
 "d3":[["akseki-town","Highland town with wooden mosques"],[None,"Çığlıkara cedar forest — thousand-year-old trees at 1,800 m"],["gombe-yesil-gol","Green tarn under Akdağ, a two-hour walk in"]],
 "note":"Altınbeşik only floods enough for boats from about March to June — outside that window you walk in and see mud."},

{"id":"r-hatay-cilicia","title":"Cilicia and Hatay: Mosaics, Castles and the Best Food in Türkiye","region":"Mediterranean","days":"5 days","mode":"car","ap":"ADA","hub":"Adana","season":"Mar–May, Oct–Nov","stay":["Antakya","Check what has reopened since 2023 before booking"],
 "d1":[["adana-stone-bridge","Roman bridge, then kebap and şalgam for lunch"],["sabanci-merkez-mosque","Six minarets by the river"],["varda-viaduct","The German-built railway viaduct in the gorge north of town"]],
 "d2":[["karatepe-aslantas","Hittite reliefs in a pine wood above the lake"],["anavarza-anazarbus","Triumphal arch and a citadel on a rock spine"],["yilankale-snake-castle","Armenian castle with the whole plain below"]],
 "d3":[["hatay-mosaic-museum","One of the great Roman mosaic collections anywhere"],["st-pierre-church-antakya","Cave church cut into Mount Silpius"],["antakya-old-town","Walk what has been rebuilt, and eat künefe"]],
 "d4":[["titus-tunnel-cevlik","Roman flood tunnel hacked through a hillside by hand"],["vakifli-armenian-village","The last Armenian village in Türkiye, on Musa Dağı"],["samandag-coast","Long grey-sand beach at the river mouth"]],
 "d5":[["kizkalesi-maidens-castle","Castle on an island 200 m offshore — swim out"],["cennet-cehennem-sinkholes","Heaven and Hell, and the chapel at the bottom of Heaven"],["kanlidivane-canytelis","Reliefs cut into the walls of an enormous sinkhole"],["uzuncaburc-diocaesarea","Zeus temple columns in a mountain village"]],
 "note":"Hatay was hit hard by the 2023 earthquakes and parts of Antakya are still rebuilding. Going and spending money there is welcome; going expecting the old town intact is not realistic."},

{"id":"r-isparta-lakes","title":"The Lake District: Eğirdir, Salda and Sagalassos","region":"Mediterranean","days":"4 days","mode":"car","ap":"ISE","hub":"Isparta","season":"May–Jun, Sep–Oct","stay":["Eğirdir","Guesthouses out on Yeşilada, the island in the lake"],
 "d1":[["egirdir-lake-yesilada","Sunset from the island causeway"],["isparta-rose-harvest","In late May and June the whole valley smells of it"]],
 "d2":[["sagalassos","A Roman city at 1,500 m with a fountain that still runs"],["aglasun-town","Lunch in the village below"],["kibyra-ancient-city","Stadium and the Medusa mosaic in the odeon"]],
 "d3":[["salda-lake","White magnesite shore and turquoise water — stay out of the roped-off areas"],["insuyu-cave","Underground lakes near Burdur"],["burdur-lake","Flamingos on the flats"]],
 "d4":[["kovada-lake-national-park","Forest and lake south of Eğirdir"],["yazili-canyon","Cold pools and the old Roman road through the gorge"],["antiochia-in-pisidia","Where Paul preached, above Yalvaç"]],
 "note":"Salda has been loved close to death — the fine white shore is a protected mineral deposit, and the fenced-off sections are fenced for a reason."},

{"id":"r-cappadocia-core","title":"Cappadocia: The Four Days That Matter","region":"Central Anatolia","days":"4 days","mode":"car","ap":"NAV","hub":"Göreme","season":"Apr–May, Sep–Oct","stay":["Göreme","Cave hotels; Uçhisar and Ortahisar are quieter and have the better views"],
 "d1":[["cappadocia-ballooning","Book the first morning so a cancellation still leaves you a spare day"],["goreme-open-air-museum","The painted rock churches, at opening"],["uchisar-castle","Up the rock for the whole valley at sunset"]],
 "d2":[["rose-valley-gulludere","Walk it in the late afternoon when the tuff goes pink"],["red-valley-kizilcukur","Continues from Rose Valley — one long linked walk"],["cavusin","Old village and the Vaftizci Yahya church above"],["pasabag-monks-valley","Multi-headed fairy chimneys and the hermit columns"]],
 "d3":[["derinkuyu-underground-city","Eight levels down; skip if you dislike tight spaces"],["ihlara-valley","Walk the green gorge between the churches"],["selime-monastery","Cathedral-sized rock monastery at the valley's end"]],
 "d4":[["mustafapasa-sinasos","Greek stone carving in a quiet village"],["soganli-valley","Two valleys of churches with almost nobody in them"],["ortahisar","Finish at the rock castle and a terrace"]],
 "note":"The balloons only fly in the hour after dawn and are cancelled for wind more often than the brochures admit. Book day one, and treat day four as your backup."},

{"id":"r-cappadocia-deep","title":"Cappadocia Without the Crowds","region":"Central Anatolia","days":"3 days","mode":"car","ap":"NAV","hub":"Ürgüp","season":"Apr–May, Oct–Nov","stay":["Güzelyurt","A stone village on the Aksaray side with almost no tourism"],
 "d1":[["zelve-open-air-museum","Three valleys of cave dwellings lived in until 1952"],["devrent-valley","No churches, just the strangest rock shapes"],["ozkonak-underground-city","Smaller and emptier than Derinkuyu"],["avanos","Red-clay pottery on the Kızılırmak"]],
 "d2":[["guzelyurt-gelveri","Monastery valley and Greek houses"],["hasan-dagi","The volcano that made all this; drive to the treeline"],["asikli-hoyuk","A 10,000-year-old village mound being excavated"]],
 "d3":[["gumusler-monastery","The best-preserved frescoes in Cappadocia, and no queue"],["narligol-crater-lake","Hot spring in a crater on the way"],["soganli-valley","End here if you have not already"]],
 "note":"Everything on this route is within an hour of Göreme, and on most days you will share it with nobody. The trade-off is that you need a car."},

{"id":"r-konya-steppe","title":"Konya, Çatalhöyük and the Steppe","region":"Central Anatolia","days":"4 days","mode":"car","ap":"KYA","hub":"Konya","season":"Apr–Jun, Sep–Oct","stay":["Konya","Near Mevlâna for the evening call to prayer over the green dome"],
 "d1":[["mevlana-museum","The Rumi shrine — a pilgrimage site, so dress and behave accordingly"],["alaeddin-hill","Seljuk mosque on the city's ancient mound"],["sille","Rock churches in a suburb that was Greek until 1924"]],
 "d2":[["catalhoyuk","The oldest town on earth; the shelters make more sense with the museum"],["karapinar-obruks","Sinkholes opening in the plain, some with lakes in them"],["meke-crater-lake","A volcanic cone inside a crater lake, now mostly dry"]],
 "d3":[["lake-beysehir","Reed beds and fishing villages"],["esrefoglu-mosque","A wooden hypostyle mosque with a snow well in the floor"],["kubad-abad-palace","Seljuk lakeside palace with tile fragments"]],
 "d4":[["binbir-kilise","The Thousand and One Churches on the flank of Karadağ"],["taskale-granaries","Grain stores carved into a cliff, still in use"],["manazan-caves","Multi-storey cave city across the valley"]],
 "note":"Konya is dry, conservative and one of the friendliest cities in the country. Fridays around the Mevlâna are busy; the sema ceremony runs on Saturday evenings."},

{"id":"r-phrygia","title":"The Phrygian Valleys","region":"Central Anatolia","days":"3 days","mode":"car","ap":"AOE","hub":"Eskişehir","season":"Apr–Jun, Sep–Oct","stay":["Afyonkarahisar","Thermal hotels, which after a day of walking is the correct choice"],
 "d1":[["odunpazari","Coloured Ottoman houses and the meerschaum workshops"],["midas-city-phrygian-valley","The great carved facade of Yazılıkaya"],["seyitgazi","Dervish complex on the hill above the town"]],
 "d2":[["ayazini","Rock churches and chimneys in a village nobody has heard of"],["seydiler-fairy-chimneys","Mushroom rocks with a castle carved into one"],["aslantas-yilantas","Phrygian lion and serpent tombs cut in the cliffs"]],
 "d3":[["afyonkarahisar-castle","700 steps up the black rock"],["afyonkarahisar","Sucuk, kaymak and the thermal baths"],["aizanoi","The most complete Zeus temple in Anatolia, with a vaulted undercroft"]],
 "note":"This is Cappadocia's landscape without Cappadocia's crowds or its infrastructure. Signposting is poor and a car is essential."},

{"id":"r-hattusa-plateau","title":"Hattusa, Amasya and the Northern Plateau","region":"Central Anatolia","days":"4 days","mode":"car","ap":"MZH","hub":"Amasya","season":"May–Jun, Sep–Oct","stay":["Amasya","Restored Yalıboyu houses on the river under the rock tombs"],
 "d1":[["amasya-rock-tombs","Pontic kings cut into the cliff, lit at night"],["harsena-castle-amasya","Up for the view down the gorge"],["ferhat-sirin-water-channel","The legend's canal, cut along the rock face"]],
 "d2":[["hattusa","The Hittite capital — 6 km of walls, drive the circuit"],["yazilikaya","The rock sanctuary with its procession of gods"],["alacahoyuk","Sphinx gate and the royal tombs"]],
 "d3":[["sapinuwa-ortakoy","A second Hittite capital, still being dug"],["incesu-canyon-ortakoy","Walk the gorge below with its rock-cut monastery"],["corum-leblebi","Roasted chickpeas, the town's entire identity"]],
 "d4":[["tokat-castle-latifoglu-konak","Castle and a painted Ottoman mansion"],["ballica-cave","Enormous chambers with mushroom-shaped formations"],["niksar","Danişmend capital with a good castle and quiet streets"]],
 "note":"Hattusa is far bigger than people expect — the circuit is a proper drive with stops, not a walk, and takes half a day."},

{"id":"r-safranbolu","title":"Safranbolu and the Western Black Sea","region":"Black Sea","days":"4 days","mode":"car","ap":"ONQ","hub":"Safranbolu","season":"May–Jun, Sep–Oct","stay":["Safranbolu","Konak hotels in the old town — the whole point of coming"],
 "d1":[["safranbolu","Ottoman merchant town, cobbles and timber, at its best after the day-trippers leave"],["cinci-han-safranbolu","The caravanserai in the middle of the bazaar"],["kaymakamlar-house-safranbolu","Inside a merchant house, to see how they worked"]],
 "d2":[["tokatli-canyon-incekaya-aqueduct","Glass terrace over the gorge and Ottoman aqueduct"],["yoruk-koyu","A second, emptier Ottoman village 10 km away"],["bulak-mencilis-cave","Long cave with an underground river"]],
 "d3":[["amasra","Two bays, an island and a Byzantine citadel"],["kurucasile","Wooden boatyards along the coast road"],["cide-gideros-cove","The most beautiful cove on the Black Sea, and the road to it is slow"]],
 "d4":[["kastamonu-castle-old-town","Castle, konaks and a quiet provincial centre"],["mahmutbey-mosque-kasaba","A wooden mosque with painted ceilings and no nails, now UNESCO-listed"],["kure-mountains-national-park","Canyons and beech forest on the way back"]],
 "note":"The Bartın–Cide coast road is one of the great drives in Türkiye and one of the slowest — budget three hours for 90 km and enjoy it."},

{"id":"r-trabzon-sumela","title":"Trabzon, Sümela and the Zigana Road","region":"Black Sea","days":"4 days","mode":"car","ap":"TZX","hub":"Trabzon","season":"Jun–Sep","stay":["Trabzon","Or Uzungöl for a night, mid-week and out of season"],
 "d1":[["hagia-sophia-trabzon","Byzantine frescoes above the sea"],["ataturk-kosku-trabzon","White villa in a hillside garden"],["akcaabat","Köfte for dinner where the köfte comes from"]],
 "d2":[["sumela-monastery","Book a slot; the cliff monastery is the whole reason people come"],["vazelon-monastery","The one nobody goes to, a rough track and a steep walk"],["hidirnebi-yaylasi","Cloud and meadow above Akçaabat"]],
 "d3":[["uzungol","Go early or stay overnight — by lunchtime it is a car park"],["sultan-murat-yaylasi","High pasture above the lake, far quieter"],["cal-cave","The long cave near Düzköy"]],
 "d4":[["zigana-pass","The old road over the mountains"],["santa-ruins","Abandoned Greek stone village in the forest, a real walk"],["karaca-cave-gumushane","Formations near Torul on the way back"]],
 "note":"Sümela runs a timed-entry system and sells out in summer. Uzungöl is beautiful at seven in the morning and unbearable at two in the afternoon."},

{"id":"r-firtina-kackar","title":"The Fırtına Valley and the Kaçkar Yaylas","region":"Black Sea","days":"6 days","mode":"car","ap":"TZX","hub":"Çamlıhemşin","season":"Jun–Sep","stay":["Pokut","Wooden yayla houses on the ridge; book, there are very few"],
 "d1":[["camlihemsin","Arrive up the valley, tea and orientation"],["firtina-valley","Ottoman humpback bridges the whole way up"],["zilkale","The castle in the cloud forest, best in mist"]],
 "d2":[["pokut-yaylasi","Wooden houses on a ridge above the cloud line"],["sal-yaylasi","Walk the ridge across to Sal"],["gito-yaylasi","And on to Gito if the legs hold"]],
 "d3":[["ayder-yaylasi","Busy and built-up, but the base for everything above"],["palovit-waterfall","Down the side valley to the falls"],["kackar-mountains-national-park","Walk in toward the high lakes"]],
 "d4":[["anzer-yaylasi","The honey plateau — flowers to the horizon in July"],["cayeli-tea-terraces","Back down through the tea"],["rize-ziraat-botanic-garden","Tea tasting on the terrace over Rize"]],
 "d5":[["yusufeli-coruh","Over into Artvin — see it while the valley is still recognisable"],["barhal-church","Georgian basilica now used as a mosque"],["dortkilise","A bigger, emptier church up a forest track"]],
 "d6":[["karagol-sahara-national-park","Black lake in the spruce forest at Şavşat"],["ardanuc-cehennem-canyon","Hell canyon and the road down to it"],["borcka-karagol","Reflections and a boardwalk loop on the way to Hopa"]],
 "note":"The yayla roads are unpaved, steep and often in cloud; a high-clearance car matters more than four-wheel drive. Snow closes most of this from November to May."},

{"id":"r-kars-ani","title":"Kars, Ani and the Eastern Express","region":"Eastern Anatolia","days":"4 days","mode":"rail","ap":"KSY","hub":"Kars","season":"Jun–Sep, or Jan–Feb for the snow","stay":["Kars","Russian-era stone buildings in the centre"],
 "d1":[["kars-castle-old-town","Grid streets of Russian houses, and the castle above"],["kars-kasari","Cheese, honey and a long breakfast"]],
 "d2":[["ani-ruins","A ruined Armenian capital on the border gorge — give it four hours"]],
 "d3":[["cildir-lake","Frozen in winter, with horse-drawn sleds on the ice"],["seytan-castle","Fortress on a cliff in a gorge, over in Ardahan"],["damal","The shadow of Atatürk on the mountain, if you time it right"]],
 "d4":[["sarikamis","Scots pine forest, ski slopes and the 1914 memorials"],["dogu-ekspresi","Take the train back west if you have the days for it"]],
 "note":"Ani is exposed and there is no shade or shelter — it is fierce in July and genuinely dangerous in a January wind. Bring more layers than seems sensible."},

{"id":"r-van-lake","title":"Van, Akdamar and the Lake","region":"Eastern Anatolia","days":"5 days","mode":"car","ap":"VAN","hub":"Van","season":"Jun–Sep","stay":["Van","City hotels; Gevaş for the lake shore"],
 "d1":[["van-kahvalti","Start with the breakfast street — it is a genuine institution"],["van-fortress","Urartian citadel with cuneiform and the old city ruins below"],["van-cat","The cat research centre, which is exactly as odd as it sounds"]],
 "d2":[["akdamar-island","Boat to the 10th-century Armenian church and its carved Bible in stone"],["gevas-halime-hatun","Seljuk cemetery on the shore"],["lake-van","Swim if you dare — it is soda water and startlingly soft"]],
 "d3":[["cavustepe","Urartian fortress with a temple inscription"],["hosap-castle","A fairy-tale castle on a rock above the road"],["zap-valley","On toward Hakkari if the advisories are clear"]],
 "d4":[["muradiye-waterfall","Suspension bridge over the falls"],["ercek-lake","Flamingos on a quieter lake east of the city"],["samram-canal","A 2,700-year-old irrigation canal still watering fields"]],
 "d5":[["nemrut-crater-lake","Not the statues — the huge caldera above Tatvan, with warm and cold lakes"],["ahlat-seljuk-cemetery","A forest of carved headstones above the water"],["kef-castle-adilcevaz","Urartian fortress on the way round"]],
 "note":"Van to Tatvan around the north shore is a long, spectacular drive. Check current advisories for Hakkari before adding the Zap valley."},

{"id":"r-nemrut-commagene","title":"Mount Nemrut and the Commagene","region":"Southeastern Anatolia","days":"3 days","mode":"car","ap":"ADF","hub":"Kahta","season":"Jun–Sep","stay":["Kahta","Or Karadut, halfway up the mountain, to shorten the sunrise start"],
 "d1":[["karakus-tumulus","The eagle column, best in evening light"],["cendere-bridge","Roman arch over the gorge"],["arsameia","The Heracles handshake relief and the tunnel"]],
 "d2":[["nemrut-dagi","Sunrise on the east terrace, then the west terrace as the light comes round"],["perre","Rock-cut tombs on the way back through Adıyaman"]],
 "d3":[["besni","Abandoned stone town and the castle above"],["malatya-apricots","Or head north to Malatya for the apricot harvest"],["aslantepe","The 5,000-year-old palace mound outside Malatya"]],
 "note":"The summit road closes with the first real snow, usually late October, and reopens in May. Outside that window this route does not work."},

{"id":"r-southeast-grand","title":"The Southeast: Antep, Urfa and Mardin","region":"Southeastern Anatolia","days":"8 days","mode":"car","ap":"GZT","hub":"Gaziantep","season":"Mar–May, Oct–Nov","stay":["Mardin","Three nights at the end, in a stone konak in the old town"],
 "d1":[["zeugma-mosaic-museum","Straight there from the airport — the Gypsy Girl is worth the trip alone"],["gaziantep-castle","The old city around it, and baklava"],["antep-bakircilar-carsisi","Coppersmiths, spice stalls and beyran soup"]],
 "d2":[["halfeti","Boat over the sunken village"],["rumkale","The fortress on its spur, reached only by water"],["birecik-bald-ibis","The last colony, on the cliffs above the Euphrates"]],
 "d3":[["gobekli-tepe","Twelve thousand years old, and it rewrote the timeline"],["karahan-tepe","Its stranger, emptier sibling an hour east"],["urfa-bazaar","Back in Urfa for the covered bazaar and Gümrük Han"]],
 "d4":[["harran","Beehive houses on the plain"],["sogmatar","The Sabian planet sanctuary, almost never visited"],[None,"Şuayb City — a Roman rock town 15 km on"],["han-el-barur","Caravanserai alone on the plateau at sunset"]],
 "d5":[["balikligol-urfa","Morning at the sacred pools"],[None,"A sıra gecesi evening — music, çiğ köfte and bitter mırra coffee"]],
 "d6":[["mardin-old-town","Terraces of honey stone above Mesopotamia"],["kasimiye-medrese","The life-shaped pool and the best view in town"],["deyrulzafaran","The Syriac patriarchate east of the city"]],
 "d7":[["dara-ancient-city","Byzantine rock cistern and necropolis"],["midyat","Silver workshops and stone courtyards"],["mor-gabriel","The oldest working Syriac monastery in the world"]],
 "d8":[["diyarbakir-walls","Black basalt, six kilometres of it, over the Tigris"],["on-gozlu-kopru","The ten-arched bridge at sunset"],["zerzevan-kalesi","Roman frontier fort with an intact Mithraeum on the way"]],
 "note":"This is the best long route in the country and the least travelled by foreigners. Do it in spring or autumn — in July the plain sits at 43 °C and nothing is enjoyable."},

{"id":"r-tigris-hasankeyf","title":"The Tigris: Diyarbakır, Hasankeyf and Batman","region":"Southeastern Anatolia","days":"4 days","mode":"car","ap":"DIY","hub":"Diyarbakır","season":"Mar–May, Oct–Nov","stay":["Diyarbakır","Then a night in Midyat or Mardin"],
 "d1":[["diyarbakir-walls","Walk the Mardin Kapı to Yedi Kardeş stretch"],["diyarbakir-ulu-cami","The oldest mosque in Anatolia, built from a church"],["on-gozlu-kopru","Sunset over the Tigris"]],
 "d2":[["egil","Turquoise reservoir under Assyrian rock reliefs"],["cermik-travertines","White terraces and a thermal soak"]],
 "d3":[["hasankeyf","See it honestly — most of it is under the reservoir since 2020"],["malabadi-bridge","The great Artuqid arch over the Batman river"],["hasuni-caves","Rock-cut settlement outside Batman"]],
 "d4":[["zerzevan-kalesi","The Mithraeum and the watchtower"],["dara-ancient-city","And on to Dara if you are continuing to Mardin"]],
 "note":"Hasankeyf divides people. Going expecting the town in the photographs leads to disappointment; going to see what the dam did is a different and worthwhile trip."},
]

# ------------------------------------------------------------------ month by month
MEVENTS = {
 1: [["cappadocia-ballooning","Balloons over snow-dusted chimneys — the clearest, coldest flying weather of the year"],
     ["palandoken-ski","Erzurum's slopes at their deepest, and startlingly cheap by Alpine standards"],
     ["cildir-lake","The lake freezes solid and the horse-drawn sleds come out"],
     ["dogu-ekspresi","The Eastern Express through snow country — book the sleeper months ahead"],
     ["antalya-kaleici","The Mediterranean old town at 15 °C with nobody in it"]],
 2: [["uludag","Half-term snow above Bursa, with the city an hour below"],
     ["sarikamis","Powder in the Scots pines, and the 1914 commemorations"],
     ["kartalkaya","The closest real ski to Istanbul"],
     ["cermik-travertines","Steam off the white terraces in cold air"],
     ["balikli-kaplica","The doctor-fish thermal pools at Kangal, best when it is freezing outside"]],
 3: [["patara-ancient-city","The dunes and ruins before the beach closes for nesting season"],
     ["lycian-way-western-half","The western Lycian Way at its greenest and coolest"],
     [None,"Nevruz on 21 March — fires jumped and spring declared across the east"],
     ["kaz-daglari-mount-ida","Wildflowers starting on the skirts of Mount Ida"],
     ["hierapolis","Pamukkale's travertines with spring water and thin crowds"]],
 4: [["aphrodisias","Poppies through the stadium seats — the best week of the year here"],
     [None,"Tulip season across Istanbul's parks through most of April"],
     ["sagalassos","Meltwater running through the Roman fountain at 1,500 m"],
     ["ihlara-valley","The gorge green and the river high"],
     ["mus-plain-tulips","The Muş plain turns red with wild tulips"]],
 5: [["goreme-open-air-museum","Cappadocia's perfect month — green valleys, warm days, cool nights"],
     ["isparta-rose-harvest","Rose picking starts before dawn through late May and June"],
     ["koprulu-canyon","Rafting season opens on the Köprüçay"],
     ["salda-lake","White shore and turquoise water before the summer crowds"],
     ["xanthos-ancient-city","Lycia at its best before the heat arrives"]],
 6: [["ayder-yaylasi","The eastern Black Sea greens over and the yayla roads finally open"],
     ["kackar-mountains-national-park","Snow off the passes, high lakes reachable again"],
     ["nemrut-dagi","The summit road reopens for the sunrise season"],
     ["anzer-yaylasi","Flowers to the horizon on the honey plateau"],
     ["kirkpinar-sarayici","Kırkpınar oil wrestling at Edirne, running since 1362"]],
 7: [["pokut-yaylasi","Cloud below the ridge and 18 °C while the plateau bakes"],
     ["munzur-valley-national-park","Cold clear water in Tunceli when everywhere else is 40 °C"],
     ["datca-peninsula-road","The meltemi blowing and the water finally warm"],
     ["cambasi-yaylasi","Ordu's high pastures and the yayla festivals"],
     ["gokceada","Empty Aegean island beaches with wind and no crowds"]],
 8: [["cilo-glacier","The only month the Hakkari high route is properly open — check advisories"],
     ["ani-ruins","Kars sits at 1,750 m and stays pleasant while the country boils"],
     ["karagol-sahara-national-park","Artvin's spruce forests and lakes at their best"],
     ["kafkasor-yaylasi","The Kafkasör festival above Artvin with its bull contests"],
     ["suluada-island","Turquoise water off the Antalya coast, if you can bear the prices"]],
 9: [["kekova-sunken-city","Warm sea, no crowds — the best month on the whole Turkish coast"],
     ["ephesus","Ruins comfortable again and the light turning gold"],
     ["bozcaada","Grape harvest on the island"],
     ["sirince","Figs, grapes and the fruit-wine season"],
     ["tillo-aydinlar","The equinox light beam through İbrahim Hakkı's tomb, around 23 September"]],
 10:[["yedigoller-national-park","Peak autumn colour in Bolu's seven lakes, roughly the third week"],
     ["rose-valley-gulludere","Cappadocian valleys turning copper and the poplars gold"],
     ["mardin-old-town","The southeast becomes pleasant again for the first time since May"],
     ["abant-lake","Beech and hornbeam turning above the lake"],
     ["safranbolu","Ottoman roofs, woodsmoke and the saffron harvest"]],
 11:[["hatay-mosaic-museum","Museum season — the food cities are at their best when it rains"],
     ["antep-bakircilar-carsisi","Gaziantep in jumper weather, which is how it should be eaten"],
     ["balikli-kaplica","Thermal water starts to make sense again"],
     [None,"Istanbul's grey afternoons, hamams and empty museums"],
     ["kemeralti-izmir","İzmir's bazaar without a single cruise passenger in it"]],
 12:[["cappadocia-ballooning","First snow over the fairy chimneys, and the cheapest cave hotels of the year"],
     ["mevlana-museum","The Şeb-i Arûs whirling ceremonies in Konya, 7–17 December"],
     ["palandoken-ski","Season opens properly on the Erzurum slopes"],
     ["uzungol","Snow on the Black Sea highlands and nobody in the car parks"],
     ["dogu-ekspresi","The winter run east — the reason the train has a cult following"]],
}
